# Generated by Django 5.1.7 on 2025-03-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('stock', models.FloatField()),
                ('price', models.FloatField()),
                ('price_brutto', models.FloatField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
