# Generated by Django 5.1.7 on 2025-04-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webMyApp', '0002_contact_remove_product_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
